html_table = """<table id="tablepress-21" class="tablepress tablepress-id-21 dataTable no-footer" aria-describedby="tablepress-21_info">
<caption style="caption-side:bottom;text-align:left;border:none;background:none;margin:0;padding:0;"><a href="http://wordpress/wp-admin/admin.php?page=tablepress&amp;action=edit&amp;table_id=21" rel="nofollow">Изменить</a></caption>
<thead>
<tr class="row-1 odd"><th class="column-1 sorting" tabindex="0" aria-controls="tablepress-21" rowspan="1" colspan="1" aria-label="Картриджи для принтеров: активировать для сортировки столбца по возрастанию" style="width: 588.344px;">Картриджи для принтеров</th><th class="column-2 sorting" tabindex="0" aria-controls="tablepress-21" rowspan="1" colspan="1" aria-label="Cовместимый: активировать для сортировки столбца по возрастанию" style="width: 110.625px;">Cовместимый</th><th class="column-3 sorting" tabindex="0" aria-controls="tablepress-21" rowspan="1" colspan="1" aria-label=": активировать для сортировки столбца по возрастанию" style="width: 39.1875px;"></th><th class="column-4 sorting" tabindex="0" aria-controls="tablepress-21" rowspan="1" colspan="1" aria-label="Ориг.: активировать для сортировки столбца по возрастанию" style="width: 48.4844px;">Ориг.</th><th class="column-5 sorting" tabindex="0" aria-controls="tablepress-21" rowspan="1" colspan="1" aria-label="Цвет: активировать для сортировки столбца по возрастанию" style="width: 38.3594px;">Цвет</th></tr>
</thead>
<tbody class="row-hover">















































































































































































































































































































































































































































































































<tr class="row-2 even">
	<td class="column-1"></td><td class="column-2">Цена, руб.<br>1&nbsp;шт.</td><td class="column-3"><br>10&nbsp;шт.</td><td class="column-4">Цена, руб.<br>1&nbsp;шт.</td><td class="column-5">&nbsp;</td>
</tr><tr class="row-3 odd">
	<td class="column-1"><div class="title"><a href="картридж-hp-w1106a-106a-без-чипа/"><b>HP&nbsp;W1106A (106A) БЕЗ ЧИПА</b></a></div><div class="clear"><div class="links"><div class="c-gray">Подходит к принтерам:</div><a href="/cartridge/hp/"><b>HP</b></a>:<br>
                  <a href="/printer/hp/laser-107a/">Laser 107a</a>, <a href="/printer/hp/laser-mfp-135a/">Laser MFP 135a</a></div></div></td><td class="column-2">1700          <br><a href="#add=2718" class="buy" rel="nofollow, noindex">Купить</a></td><td class="column-3">1600          <br><a href="#add=2718&amp;qty=10" class="buy" rel="nofollow, noindex">Купить</a></td><td class="column-4"></td><td class="column-5"><span style="background: black">&nbsp;</span></td>
</tr><tr class="row-4 even">
	<td class="column-1"><div class="title"><a href="/cartridge/hp/106awc/"><b>HP&nbsp;W1106A (106A) С ЧИПОМ</b></a></div><div class="clear"><div class="links"><div class="c-gray">Подходит к принтерам:</div><a href="/cartridge/brother/"><b>Brother</b></a>:<br>
                  <a href="/printer/brother/dcp-9020/">DCP-9020</a></div></div></td><td class="column-2">2100          <br><a href="#add=2834" class="buy" rel="nofollow, noindex">Купить</a></td><td class="column-3">2050          <br><a href="#add=2834&amp;qty=10" class="buy" rel="nofollow, noindex">Купить</a></td><td class="column-4">6650<br><a href="#add=-2834" class="buy" rel="nofollow, noindex">Купить</a></td><td class="column-5"><span style="background: black">&nbsp;</span></td>
</tr><tr class="row-5 odd">
	<td class="column-1"><div class="title"><a href="/cartridge/hp/cf259x/"><b>HP&nbsp;CF259X (59X) БЕЗ ЧИПА</b></a></div><div class="clear"><div class="links"><div class="c-gray">Подходит к принтерам:</div><a href="/cartridge/canon/"><b>Canon</b></a>:<br>
                  <a href="/printer/canon/mf449x/">i-Sensys MF449x</a></div></div></td><td class="column-2">1900          <br><a href="#add=2714" class="buy" rel="nofollow, noindex">Купить</a></td><td class="column-3">1800          <br><a href="#add=2714&amp;qty=10" class="buy" rel="nofollow, noindex">Купить</a></td><td class="column-4"></td><td class="column-5"><span style="background: black">&nbsp;</span></td>
</tr><tr class="row-6 even">
	<td class="column-1"><div class="title"><a href="/cartridge/hp/cf283a/"><b>HP&nbsp;CF283A (№ 83)</b></a><div class="icons"><span class="ico-action-small left" title="товар участвует в акции">&nbsp;</span><span class="left">&nbsp;</span></div></div><div class="clear"><div class="links"><div class="c-gray">Подходит к принтерам:</div><a href="/cartridge/hp/"><b>HP</b></a>:<br>
                  <a href="/printer/hp/lj-pro-m125nw/">LaserJet Pro M125NW</a>, <a href="/printer/hp/lj-pro-m127fn/">LaserJet Pro M127FN</a>, <a href="/cartridge/canon/"><b>Canon</b></a>:<br>
                  <a href="/printer/canon/i-sensys-mf226dn/">i-SENSYS MF226dn</a></div></div></td><td class="column-2">1200          <br><a href="#add=2202" class="buy" rel="nofollow, noindex">Купить</a></td><td class="column-3">1200          <br><a href="#add=2202&amp;qty=10" class="buy" rel="nofollow, noindex">Купить</a></td><td class="column-4">7950<br><a href="#add=-2202" class="buy" rel="nofollow, noindex">Купить</a></td><td class="column-5"><span style="background: black">&nbsp;</span></td>
</tr><tr class="row-7 odd">
	<td class="column-1"><div class="title"><a href="/cartridge/hp/cf218a/"><b>HP&nbsp;CF218A (18A)</b></a></div><div class="clear"><div class="links"><div class="c-gray">Подходит к принтерам:</div><a href="/cartridge/hp/"><b>HP</b></a>:<br>
                  <a href="/printer/hp/ljp-m104/">LaserJet Pro M104</a>, <a href="/printer/hp/ljp-m132fw/">LaserJet Pro M132fw</a></div></div></td><td class="column-2">1600          <br><a href="#add=2503" class="buy" rel="nofollow, noindex">Купить</a></td><td class="column-3">1500          <br><a href="#add=2503&amp;qty=10" class="buy" rel="nofollow, noindex">Купить</a></td><td class="column-4">9660<br><a href="#add=-2503" class="buy" rel="nofollow, noindex">Купить</a></td><td class="column-5"><span style="background: black">&nbsp;</span></td>
</tr><tr class="row-8 even">
	<td class="column-1"><div class="title"><a href="/cartridge/hp/ce285a/"><b>HP&nbsp;CE285A</b></a></div><div class="clear"><div class="links"><div class="c-gray">Подходит к принтерам:</div><a href="/cartridge/hp/"><b>HP</b></a>:<br>
                  <a href="/printer/hp/lj-pro-p1102/">LaserJet Pro P1102</a>, <a href="/printer/hp/lj-pro-p1102w/">LaserJet Pro P1102w</a>, <a href="/printer/hp/ljp-m1132-mfp/">LaserJet Pro M1132 MFP (МФУ)</a>, <a href="/printer/hp/p1120/">P1120</a>, <a href="/printer/hp/lj-pro-m1212-mfp/">LaserJet Pro M1212 MFP</a>, <a href="/printer/hp/lj-pro-m1214nfh/">LaserJet Pro M1214nfh</a>, <a href="/printer/hp/lj-pro-m1217nfw/">LaserJet Pro M1217nfw</a>, <a href="/cartridge/canon/"><b>Canon</b></a>:<br>
                  <a href="/printer/canon/lbp6030b/">i-Sensys LBP6030B (8468B006)</a></div></div></td><td class="column-2">1290          <br><a href="#add=1054" class="buy" rel="nofollow, noindex">Купить</a></td><td class="column-3">1190          <br><a href="#add=1054&amp;qty=10" class="buy" rel="nofollow, noindex">Купить</a></td><td class="column-4"></td><td class="column-5"><span style="background: black">&nbsp;</span></td>
</tr><tr class="row-9 odd">
	<td class="column-1"><div class="title"><a href="/cartridge/hp/cf280x/"><b>HP&nbsp;CF280X</b></a></div><div class="clear"><div class="links"><div class="c-gray">Подходит к принтерам:</div><a href="/cartridge/hp/"><b>HP</b></a>:<br>
                  <a href="/printer/hp/ljp-400-m401dn/">LaserJet Pro 400 M401dn</a></div></div></td><td class="column-2">1800          <br><a href="#add=1638" class="buy" rel="nofollow, noindex">Купить</a></td><td class="column-3">1700          <br><a href="#add=1638&amp;qty=10" class="buy" rel="nofollow, noindex">Купить</a></td><td class="column-4"></td><td class="column-5"><span style="background: black">&nbsp;</span></td>
</tr><tr class="row-10 even">
	<td class="column-1"><div class="title"><a href="/cartridge/hp/q2612a/"><b>HP&nbsp;Q2612A</b></a><div class="icons"><span class="ico-logistic-small left" title="круглосуточная доставка">&nbsp;</span></div></div><div class="clear"><div class="links"><div class="c-gray">Подходит к принтерам:</div><a href="/cartridge/hp/"><b>HP</b></a>:<br>
                  <a href="/printer/hp/lj-1010/">LaserJet 1010</a>, <a href="/printer/hp/lj-1012/">LaserJet 1012</a>, <a href="/printer/hp/lj-1015/">LaserJet 1015</a>, <a href="/printer/hp/lj-1020/">LaserJet 1020</a>, <a href="/printer/hp/lj-1022/">LaserJet 1022</a>, <a href="/printer/hp/lj-1022n/">LaserJet 1022n</a>, <a href="/printer/hp/lj-1022nw/">LaserJet 1022nw</a>, <a href="/printer/hp/lj-3015/">LaserJet 3015</a>, <a href="/printer/hp/lj-3020/">LaserJet 3020</a>, <a href="/printer/hp/lj-3030/">LaserJet 3030</a>, <a href="/printer/hp/lj-3050/">LaserJet 3050</a>, <a href="/printer/hp/lj-3050z/">LaserJet 3050z</a>, <a href="/printer/hp/lj-3052/">LaserJet 3052</a>, <a href="/printer/hp/lj-m1005/">LaserJet M1005</a>, <a href="/printer/hp/lj-m1319f/">LaserJet M1319f</a>, <a href="/cartridge/canon/"><b>Canon</b></a>:<br>
                  <a href="/printer/canon/ls-lbp2900/">Laser Shot LBP2900</a>, <a href="/printer/canon/ls-lbp3000/">Laser Shot LBP3000</a>, <a href="/printer/canon/ls-lbp-2900b/">Laser Shot LBP2900B</a>, <a href="/cartridge/hp/"><b>HP</b></a>:<br>
                  <a href="/printer/hp/lj-1018/">LaserJet 1018</a>, <a href="/printer/hp/lj-3055/">LaserJet 3055</a></div></div></td><td class="column-2">1290          <br><a href="#add=9" class="buy" rel="nofollow, noindex">Купить</a></td><td class="column-3">1190          <br><a href="#add=9&amp;qty=10" class="buy" rel="nofollow, noindex">Купить</a></td><td class="column-4"></td><td class="column-5"><span style="background: black">&nbsp;</span></td>
</tr><tr class="row-11 odd">
	<td class="column-1"><div class="title"><a href="/cartridge/hp/cb435a/"><b>HP&nbsp;CB435A</b></a><div class="icons"><span class="ico-logistic-small left" title="круглосуточная доставка">&nbsp;</span></div></div><div class="clear"><div class="links"><div class="c-gray">Подходит к принтерам:</div><a href="/cartridge/hp/"><b>HP</b></a>:<br>
                  <a href="/printer/hp/lj-p1005/">LaserJet P1005</a>, <a href="/printer/hp/lj-p1006/">LaserJet P1006</a>, <a href="/cartridge/canon/"><b>Canon</b></a>:<br>
                  <a href="/printer/canon/i-sensys-lbp3010/">i-SENSYS LBP3010</a>, <a href="/printer/canon/i-sensys-lbp3010b/">i-SENSYS LBP3010B</a>, <a href="/printer/canon/i-sensys-lbp3020/">i-SENSYS LBP3020</a>, <a href="/printer/canon/i-sensys-lbp3100/">i-SENSYS LBP3100</a></div></div></td><td class="column-2">1290          <br><a href="#add=148" class="buy" rel="nofollow, noindex">Купить</a></td><td class="column-3">1190          <br><a href="#add=148&amp;qty=10" class="buy" rel="nofollow, noindex">Купить</a></td><td class="column-4"></td><td class="column-5"><span style="background: black">&nbsp;</span></td>
</tr></tbody>
</table>"""